version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"  # map nginx 80 to local 5173 so dev port is consistent
    depends_on:
      - backend
