name: Docker CI (build + push)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build, Push & Update Containers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: chmudasir007/nta-frontend:latest

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: chmudasir007/nta-backend:latest

      - name: Stop existing frontend container
        run: docker stop nta-frontend-1 || true

      - name: Remove existing frontend container
        run: docker rm nta-frontend-1 || true

      - name: Run updated frontend container
        run: docker run -d --name nta-frontend-1 -p 5173:80 chmudasir007/nta-frontend:latest

      - name: Stop existing backend container
        run: docker stop nta-backend-1 || true

      - name: Remove existing backend container
        run: docker rm nta-backend-1 || true

      - name: Run updated backend container
        run: docker run -d --name nta-backend-1 -p 8080:8080 chmudasir007/nta-backend:latest
